import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const pcodeMap = {
  en: {
    "MMR001": "Sagaing Region",
    "MMR002": "Bago Region",
    "MMR003": "Magway Region",
    "MMR004": "Mandalay Region",
    "MMR005": "Tanintharyi Region",
    "MMR006": "Ayeyarwady Region",
    "MMR007": "Kachin State",
    "MMR008": "Kayah State",
    "MMR009": "Kayin State",
    "MMR010": "Chin State",
    "MMR011": "Mon State",
    "MMR012": "Rakhine State",
    "MMR013": "Shan State (North)",
    "MMR014": "Yangon Region",
    "MMR015": "Nay Pyi Taw",
    "MMR016": "Shan State (South)",
    "MMR017": "Shan State (East)",
    "MMR018": "Bago Region (East)"
  },
  my: {
    "MMR001": "စစ်ကိုင်းတိုင်းဒေသကြီး",
    "MMR002": "ပဲခူးတိုင်းဒေသကြီး",
    "MMR003": "မကွေးတိုင်းဒေသကြီး",
    "MMR004": "မန္တလေးတိုင်းဒေသကြီး",
    "MMR005": "တနင်္သာရီတိုင်းဒေသကြီး",
    "MMR006": "ဧရာဝတီတိုင်းဒေသကြီး",
    "MMR007": "ကချင်ပြည်နယ်",
    "MMR008": "ကယားပြည်နယ်",
    "MMR009": "ကရင်ပြည်နယ်",
    "MMR010": "ချင်းပြည်နယ်",
    "MMR011": "မွန်ပြည်နယ်",
    "MMR012": "ရခိုင်ပြည်နယ်",
    "MMR013": "ရှမ်းပြည်နယ် (မြောက်ပိုင်း)",
    "MMR014": "ရန်ကုန်တိုင်းဒေသကြီး",
    "MMR015": "နေပြည်တော်",
    "MMR016": "ရှမ်းပြည်နယ် (တောင်ပိုင်း)",
    "MMR017": "ရှမ်းပြည်နယ် (အရှေ့ပိုင်း)",
    "MMR018": "ပဲခူးတိုင်းဒေသကြီး (အရှေ့ပိုင်း)"
  }
};

const translations = {
  en: {
    "nav.landing": "Landing Page",
    "nav.home": "Home",
    "nav.fieldHealth": "Field health",
    "nav.cropPlanner": "Crop planner",
    "nav.cropGuide": "Crop guide",
    "nav.aiGuide": "AI guide",
    "nav.workspace": "Workspace",
    "nav.farmIntelligence": "Farm intelligence",
    "nav.sidebarDescription": "Clear tools for healthier fields and better crop decisions.",
    "nav.navigate": "Navigate",
    "nav.close": "Close navigation",
    "nav.open": "Open navigation",
    "nav.mobileFooter": "Field intelligence for clearer farming decisions.",
    "nav.workspaceNavigation": "Workspace navigation",
    "nav.mobileWorkspaceNavigation": "Mobile workspace navigation",
    "nav.workspaceSidebar": "Workspace sidebar",
    "brand.home": "GreenVista home",
    "language.selector": "Language selector",
    "common.skipToMain": "Skip to main content",
    "sidebar.title": "Farm Intelligence",
    "sidebar.subtitle": "Clean monitoring and diagnosis for healthy crops.",
    "language.english": "English",
    "language.burmese": "Burmese",
    "app.analytics": "MyanGrow Analytics",

    // App/Sidebar
    "app.title": "AgriDash",
    "nav.ndvi": "NDVI Analysis",
    "nav.suggestion": "Crop Suggestion",
    "nav.chat": "AI Chat",
    "account.kicker": "FARMER ACCOUNT",
    "account.title": "My farm workspace",
    "account.subtitle": "Save your farm context and return to useful analysis faster.",
    "account.setupProfile": "Set up your farm profile",
    "account.editProfile": "Edit farm profile",
    "account.requiredProfile": "Complete farm name, location, area, and soil type to personalize your workspace.",
    "account.farmLocation": "Region and district",
    "account.chooseLocation": "Choose a region and district",
    "account.soilPlaceholder": "Choose or type a soil type",
    "account.soilHelp": "Choose the soil name that farmers commonly use in your area.",
    "account.farmProfile": "Farm profile",
    "account.farmName": "Farm name",
    "account.regionCode": "Region code",
    "account.area": "Farm area (acres)",
    "account.soilType": "Soil type",
    "account.notes": "Notes",
    "account.saveProfile": "Save profile",
    "account.monitoring": "Monitoring preferences",
    "account.monitorRegion": "Monitoring region",
    "account.frequency": "Update reminder",
    "account.enableMonitoring": "Enable monitoring reminders",
    "account.ndviAlerts": "NDVI alerts",
    "account.marketAlerts": "Market alerts",
    "account.savePreferences": "Save preferences",
    "account.favorites": "Favorite crops",
    "account.history": "Recommendation history",
    "account.noFavorites": "Favorite a crop from a recommendation to see it here.",
    "account.noHistory": "Saved recommendations will appear here.",
    "account.saved": "Farm profile saved.",
    "account.preferencesSaved": "Monitoring preferences saved.",
    "account.analysisSaved": "Analysis saved to your account.",
    "account.cropSaved": "Crop added to favorites.",
    "account.saveAnalysis": "Save analysis",
    "account.favorite": "Favorite crop",
    "account.signInToSave": "Sign in to save",
    "account.farmPlaceholder": "e.g. My family farm",
    "account.acres": "acres",
    "account.removeFavorite": "Remove {crop}",
    "account.requestError": "Unable to update your account.",

    // NDVI Analysis
    "ndvi.title": "NDVI Satellite Analysis",
    "ndvi.subtitle": "Monitor crop health from space! NDVI uses satellite images to measure how green and healthy plants are.",
    "ndvi.selectRegion": "Select Region:",
    "ndvi.mapTitle": "Choose on map",
    "ndvi.mapHint": "Click the map to select the nearest analysis region.",
    "ndvi.mapMyanmar": "Myanmar",
    "ndvi.outsideMyanmar": "Please click inside Myanmar to select an analysis region.",
    "ndvi.latestVim": "Current Greenness (VIM)",
    "ndvi.avgVim": "Historical Greenness (5yr)",
    "ndvi.latestViq": "Quality vs Average (VIQ)",
    "ndvi.loading": "Loading satellite data...",
    "ndvi.location": "NDVI LOCATION",
    "ndvi.stateRegion": "State or Region",
    "ndvi.districtDetail": "Optional district detail",
    "ndvi.allDistricts": "All districts (state overview)",
    "ndvi.loadingData": "Loading NDVI data...",
    
    // NDVI Explanations
    "ndvi.whatIsNdvi": "What do these numbers mean?",
    "ndvi.vimDesc": "VIM (Greenness Index): A score measuring the actual density and health of vegetation. Higher numbers mean greener, thicker crops.",
    "ndvi.viqDesc": "VIQ (Quality Percentile): Compares current health to historical averages. Above 50 means better than normal, below 50 means worse than normal.",
    "ndvi.correlationKicker": "ENVIRONMENTAL RELATIONSHIP",
    "ndvi.correlationTitle": "What changes with vegetation health?",
    "ndvi.correlationSubtitle": "Pearson correlation between monthly mean NDVI and project soil and climate observations.",
    "ndvi.correlationSoilPh": "Soil pH",
    "ndvi.correlationRainfall": "Rainfall",
    "ndvi.correlationTemperature": "Temperature",
    "ndvi.correlationRegional": "Regional observations",
    "ndvi.correlationNational": "National environmental reference",
    "ndvi.correlationLoading": "Calculating environmental correlations...",
    "ndvi.correlationError": "Unable to calculate environmental correlations.",
    "ndvi.correlationStrong": "Strong",
    "ndvi.correlationModerate": "Moderate",
    "ndvi.correlationWeak": "Weak",
    "ndvi.correlationVeryWeak": "Very weak",
    "ndvi.correlationPositive": "positive",
    "ndvi.correlationNegative": "negative",
    "ndvi.correlationNeutral": "no clear direction",
    "ndvi.correlationUnavailable": "Not enough variation",
    "ndvi.correlationBasedOn": "Based on",
    "ndvi.correlationMonths": "paired months",
    "ndvi.correlationCaveat": "Correlation shows association, not cause.",

    // Crop Suggestion
    "crop.pageEyebrow": "Smart crop planning",
    "crop.benefitSatellite": "Satellite weather",
    "crop.benefitLocal": "Local conditions",
    "crop.benefitGuidance": "Practical guidance",
    "crop.fieldData": "Field data",
    "crop.chooseSource": "Choose your data source",
    "crop.currentLocation": "Use current field location",
    "crop.retrieveWeather": "Retrieve regional weather conditions from your coordinates.",
    "crop.chooseOnMap": "Choose a location on the map",
    "crop.mapHint": "Click a point to load matching weather and soil conditions.",
    "crop.ownMeasurements": "Use your own measurements",
    "crop.enterReadings": "Enter recent soil and weather readings in the next step.",
    "crop.growingConditions": "Growing conditions",
    "crop.reviewField": "Review your field",
    "crop.currentConditions": "Based on current conditions",
    "crop.growingProfile": "Growing profile",
    "crop.yearGrowth": "year growth period",
    "crop.waterNeed": "water-need units/day",
    "crop.latestMarketPrice": "Latest market price",
    "crop.suitable": "suitable",
    "crop.chooseCrop": "Choose a crop recommendation",
    "crop.option": "Option",
    "crop.marketValue": "Market value",
    "crop.productWeight": "Product weight (kg)",
    "crop.estimatedValue": "Estimated value",
    "common.close": "Close",
    "common.loading": "Loading your workspace...",
    "crop.plannerBenefits": "Planner benefits",
    "crop.modelConfidence": "model confidence",
    "crop.bestSeason": "Best season",
    "crop.harvestTime": "Harvest time",
    "crop.waterNeedLabel": "Water need",
    "crop.varies": "Varies",
    "crop.dialogLabel": "Crop suggestion",
    "crop.projectHistory": "Project history",
    "crop.rangeError": "{field} must be between {min} and {max}{unit}.",
    "crop.invalidNumbers": "Please enter valid numbers for all crop conditions.",
    "crop.fallbackMatch": "{crop} is the best rule-based match for the supplied conditions.",
    "crop.suggestionError": "Unable to get a crop suggestion.",
    "requirements.eyebrow": "Crop knowledge",
    "requirements.pageTitle": "Know what every crop needs.",
    "requirements.pageSubtitle": "Explore practical growing conditions before you choose what to plant.",
    "requirements.searchEyebrow": "Search the crop library",
    "requirements.title": "Find a crop's growing needs",
    "requirements.subtitle": "Search a crop to see the average climate and light conditions it needs.",
    "requirements.searchLabel": "Crop name",
    "requirements.placeholder": "Search for rice, corn, mint...",
    "requirements.search": "Search crop",
    "requirements.searching": "Searching...",
    "requirements.enterCrop": "Enter a crop name to search.",
    "requirements.notFound": "No matching crop was found.",
    "requirements.error": "Unable to load crop requirements.",
    "requirements.resultFor": "Growing requirements for",
    "requirements.temperature": "Average temperature",
    "requirements.waterNeed": "Water needed",
    "requirements.soilPh": "Average soil pH",
    "requirements.humidity": "Average humidity",
    "requirements.light": "Light intensity",
    "requirements.empty": "Search for a crop to view its preferred growing conditions.",
    "requirements.suggestionsLabel": "Crop name suggestions",
    "requirements.popularSuggestions": "Popular searches",
    "requirements.matchingSuggestions": "Matching crops",
    "requirements.suitableRegions": "Suitable regions",
    "requirements.suitableRegionsHint": "Estimated from project climate, crop-history, and Myanmar boundary datasets.",
    "requirements.matchSuffix": "% match",
    "requirements.regionCaveat": "Use this as a regional guide and confirm your township's current field conditions.",
    "crop.title": "AI Crop Suggestion",
    "crop.subtitle": "Auto-detect your location to get real satellite weather data and smart crop recommendations.",
    "crop.soilPh": "Soil pH Level",
    "crop.rainfall": "Rainfall (7-day, mm)",
    "crop.temp": "Average Temperature (°C)",
    "crop.farmArea": "Farm area (acres)",
    "crop.analyzing": "Analyzing...",
    "crop.suggestBtn": "Get Suggestion",
    "crop.recommended": "Recommended Crop",
    "crop.analysis": "AI Analysis",
    "crop.fillForm": "Detect your location or enter conditions manually to receive a suggestion.",
    "crop.error": "Crop suggestions are not available in this frontend demo.",

    // Location & Weather
    "loc.detect": "Detect My Location",
    "loc.detecting": "Detecting location...",
    "loc.fetchWeather": "Fetching satellite data...",
    "loc.permDenied": "Location permission denied. Please enable GPS or enter values manually.",
    "loc.error": "Could not detect location. Please enter values manually.",
    "loc.region": "Detected Region",
    "loc.coordinates": "Coordinates",
    "loc.currentTemp": "Current Temperature",
    "loc.rain7d": "Rainfall (7 days)",
    "loc.humidity": "Humidity",
    "loc.soilPh": "Est. Soil pH",
    "loc.source": "Data: NASA POWER Satellite",
    "loc.phNote": "Regional estimate — adjust if you have soil test results",
    "loc.advisories": "Smart Advisories",
    "loc.override": "You can adjust values before getting a suggestion",
    "loc.manualMode": "Enter Manually",
    "loc.autoMode": "Use Satellite Data",
    
    // AI Chat
    "chat.title": "AI Chat",
    "chat.powered": "Powered by Gemma 4 (Local AI)",
    "chat.placeholder": "Ask about agriculture, crops, climate...",
    "chat.error": "Sorry, I encountered an error connecting to the local LLM.",
    "chat.welcome": "Hello! I am your AI agricultural assistant for Myanmar. How can I help you today?",
    "chat.history": "Chat history",
    "chat.newChat": "New chat",
    "chat.noHistory": "Your saved conversations will appear here.",
    "chat.signInHistory": "Saved on this device. Sign in to also sync conversations to your account.",
    "chat.historyError": "Unable to load chat history.",
    "chat.saveError": "The reply was received, but the conversation could not be saved.",
    "chat.deleteError": "Unable to delete this conversation.",
    "chat.deleteChat": "Delete conversation",
    "chat.deleteConfirm": "Delete this conversation permanently?",
    "chat.send": "Send message",

    // Auth
    "auth.welcomeBack": "Welcome Back",
    "auth.createAccount": "Create Account",
    "auth.loginSubtitle": "Sign in to access your GreenVista dashboard",
    "auth.registerSubtitle": "Join GreenVista and start managing your farm",
    "auth.loginBtn": "Sign In",
    "auth.registerBtn": "Sign Up",
    "auth.logout": "Sign out",
    "auth.fillFields": "Please fill in all fields",
    "auth.passwordMismatch": "Passwords do not match",
    "auth.email": "Email Address",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm Password",
    "auth.invalidCredentials": "Invalid email or password.",
    "auth.noAccount": "Don't have an account?",
    "auth.haveAccount": "Already have an account?",
    "auth.switchSignup": "Sign Up",
    "auth.switchSignin": "Sign In",
    "auth.closeDialog": "Close authentication dialog",
    "auth.showPassword": "Show password",
    "auth.hidePassword": "Hide password",
    "auth.showConfirmPassword": "Show confirm password",
    "auth.hideConfirmPassword": "Hide confirm password",
    "auth.requestError": "Unable to complete authentication. Please try again.",
    "ndvi.regionsError": "Unable to load NDVI regions.",
    "ndvi.measurementsError": "Unable to load NDVI measurements for this region.",
  },
  my: {
    "nav.landing": "ပင်မစာမျက်နှာ",
    "nav.home": "ပင်မစာမျက်နှာ",
    "nav.fieldHealth": "လယ်ကွင်းကျန်းမာရေး",
    "nav.cropPlanner": "သီးနှံစီမံကိန်း",
    "nav.cropGuide": "သီးနှံလမ်းညွှန်",
    "nav.aiGuide": "AI လမ်းညွှန်",
    "nav.workspace": "လုပ်ငန်းခွင်",
    "nav.farmIntelligence": "လယ်ယာအချက်အလက်",
    "nav.sidebarDescription": "ကျန်းမာသောလယ်ကွင်းများနှင့် ပိုမိုကောင်းမွန်သော သီးနှံဆုံးဖြတ်ချက်များအတွက် ရှင်းလင်းသောကိရိယာများ။",
    "nav.navigate": "သွားရန်",
    "nav.close": "လမ်းညွှန်မှု ပိတ်ရန်",
    "nav.open": "လမ်းညွှန်မှု ဖွင့်ရန်",
    "nav.mobileFooter": "ပိုမိုရှင်းလင်းသော စိုက်ပျိုးရေးဆုံးဖြတ်ချက်များအတွက် လယ်ယာအချက်အလက်။",
    "sidebar.title": "လယ်ယာ အသိဉာဏ်စနစ်",
    "sidebar.subtitle": "ကျန်းမာသောသီးနှံများအတွက် စောင့်ကြည့်ခြင်းနှင့် ရောဂါရှာဖွေခြင်း။",
    "language.english": "English", "language.burmese": "မြန်မာ",
    "app.analytics": "MyanGrow စိုက်ပျိုးရေး သုံးသပ်ချက်",

    // App/Sidebar
    "app.title": "စိုက်ပျိုးရေးဒက်ရှ်ဘုတ်",
    "nav.ndvi": "NDVI ဂြိုလ်တုပုံရိပ်",
    "nav.suggestion": "သီးနှံအကြံပြုချက်",
    "nav.chat": "AI စကားပြောခန်း",

    // NDVI Analysis
    "ndvi.title": "NDVI ဂြိုလ်တု ခွဲခြမ်းစိတ်ဖြာခြင်း",
    "ndvi.subtitle": "အာကာသမှနေ၍ သီးနှံများ၏ ကျန်းမာရေးကို စောင့်ကြည့်ပါ! NDVI ဆိုတာ ဂြိုလ်တုပုံရိပ်များကို အသုံးပြုပြီး အပင်များ ဘယ်လောက် စိမ်းလန်းကျန်းမာနေသလဲဆိုတာကို တိုင်းတာပေးတာပါ။",
    "ndvi.selectRegion": "ဒေသရွေးချယ်ပါ:",
    "ndvi.mapTitle": "မြေပုံပေါ်မှ ရွေးချယ်ပါ",
    "ndvi.mapHint": "မြေပုံပေါ်တွင် နှိပ်၍ အနီးဆုံး ခွဲခြမ်းစိတ်ဖြာမည့် ဒေသကို ရွေးချယ်ပါ။",
    "ndvi.mapMyanmar": "မြန်မာနိုင်ငံ",
    "ndvi.latestVim": "လက်ရှိ စိမ်းလန်းမှု (VIM)",
    "ndvi.avgVim": "ယခင် စိမ်းလန်းမှု (၅ နှစ်)",
    "ndvi.latestViq": "ယခင်နှစ်များနှင့် နှိုင်းယှဉ်ချက် (VIQ)",
    "ndvi.loading": "ဂြိုလ်တုဒေတာ ရယူနေသည်...",

    // NDVI Explanations
    "ndvi.whatIsNdvi": "ဤဂဏန်းများက ဘာကိုဆိုလိုသနည်း?",
    "ndvi.vimDesc": "VIM (စိမ်းလန်းမှု အညွှန်းကိန်း): အပင်များ၏ သိပ်သည်းဆနှင့် ကျန်းမာရေးကို တိုင်းတာသော အမှတ်။ ဂဏန်းပိုများလေ သီးနှံများ ပိုမိုစိမ်းလန်းထူထပ်လေ ဖြစ်သည်။",
    "ndvi.viqDesc": "VIQ (အရည်အသွေး ရာခိုင်နှုန်း): လက်ရှိကျန်းမာရေးကို ယခင်နှစ်များ၏ ပျမ်းမျှအခြေအနေနှင့် နှိုင်းယှဉ်ပြသည်။ ၅၀ အထက်ဆိုလျှင် ပုံမှန်ထက် ပိုကောင်းပြီး၊ ၅၀ အောက်ဆိုလျှင် ပုံမှန်ထက် ဆိုးရွားသည်ဟု ဆိုလိုသည်။",
    "ndvi.correlationKicker": "ပတ်ဝန်းကျင်ဆိုင်ရာ ဆက်နွယ်မှု",
    "ndvi.correlationTitle": "အပင်စိမ်းလန်းကျန်းမာမှုနှင့် မည်သည့်အချက်များ ဆက်နွယ်နေသနည်း။",
    "ndvi.correlationSubtitle": "လစဉ်ပျမ်းမျှ NDVI နှင့် ပရောဂျက်ရှိ မြေဆီလွှာ၊ ရာသီဥတုမှတ်တမ်းများအကြား Pearson ဆက်နွယ်မှု။",
    "ndvi.correlationSoilPh": "မြေဆီလွှာ pH",
    "ndvi.correlationRainfall": "မိုးရေချိန်",
    "ndvi.correlationTemperature": "အပူချိန်",
    "ndvi.correlationRegional": "ဒေသဆိုင်ရာ မှတ်တမ်းများ",
    "ndvi.correlationNational": "နိုင်ငံအဆင့် ပတ်ဝန်းကျင်ကိုးကားချက်",
    "ndvi.correlationLoading": "ပတ်ဝန်းကျင်ဆိုင်ရာ ဆက်နွယ်မှုကို တွက်ချက်နေသည်...",
    "ndvi.correlationError": "ပတ်ဝန်းကျင်ဆိုင်ရာ ဆက်နွယ်မှုကို တွက်ချက်၍ မရပါ။",
    "ndvi.correlationStrong": "အားကောင်း",
    "ndvi.correlationModerate": "အသင့်အတင့်",
    "ndvi.correlationWeak": "အားနည်း",
    "ndvi.correlationVeryWeak": "အလွန်အားနည်း",
    "ndvi.correlationPositive": "အပြုသဘောဆက်နွယ်မှု",
    "ndvi.correlationNegative": "အနုတ်သဘောဆက်နွယ်မှု",
    "ndvi.correlationNeutral": "ဦးတည်ချက် မရှင်းလင်း",
    "ndvi.correlationUnavailable": "ကွဲပြားမှု မလုံလောက်ပါ",
    "ndvi.correlationBasedOn": "အခြေခံထားသော တွဲဖက်လများ",
    "ndvi.correlationMonths": "လ",
    "ndvi.correlationCaveat": "ဆက်နွယ်မှုသည် အကြောင်းရင်းဖြစ်ကြောင်း မဆိုလိုပါ။",

    // Crop Suggestion
    "crop.pageEyebrow": "သီးနှံစီမံကိန်း",
    "crop.benefitSatellite": "ဂြိုဟ်တုရာသီဥတု",
    "crop.benefitLocal": "ဒေသအခြေအနေ",
    "crop.benefitGuidance": "လက်တွေ့လမ်းညွှန်ချက်",
    "crop.fieldData": "လယ်ကွင်းအချက်အလက်",
    "crop.chooseSource": "အချက်အလက်ရင်းမြစ် ရွေးချယ်ပါ",
    "crop.currentLocation": "လက်ရှိလယ်ကွင်းတည်နေရာကို အသုံးပြုရန်",
    "crop.retrieveWeather": "သင့်တည်နေရာမှ ဒေသဆိုင်ရာရာသီဥတုအခြေအနေကို ရယူပါ။",
    "crop.ownMeasurements": "သင့်ကိုယ်ပိုင်တိုင်းတာချက်များကို အသုံးပြုရန်",
    "crop.enterReadings": "နောက်တစ်ဆင့်တွင် မြေနှင့်ရာသီဥတု တိုင်းတာချက်များကို ထည့်ပါ။",
    "crop.growingConditions": "စိုက်ပျိုးမှုအခြေအနေများ",
    "crop.reviewField": "သင့်လယ်ကွင်းကို စစ်ဆေးပါ",
    "crop.currentConditions": "လက်ရှိအခြေအနေအပေါ် အခြေခံ၍",
    "crop.growingProfile": "စိုက်ပျိုးမှုအချက်အလက်",
    "crop.yearGrowth": "နှစ် ကြီးထွားကာလ",
    "crop.waterNeed": "တစ်နေ့ ရေလိုအပ်ချက်ယူနစ်",
    "crop.latestMarketPrice": "နောက်ဆုံးစျေးကွက်စျေးနှုန်း",
    "crop.chooseCrop": "သီးနှံရွေးချယ်ပါ",
    "crop.option": "ရွေးချယ်မှု",
    "crop.marketValue": "စျေးကွက်တန်ဖိုး",
    "crop.productWeight": "ထွက်ကုန်အလေးချိန် (ကီလိုဂရမ်)",
    "crop.estimatedValue": "ခန့်မှန်းတန်ဖိုး",
    "common.close": "ပိတ်ရန်",
    "crop.title": "AI သီးနှံအကြံပြုချက်",
    "crop.subtitle": "သင့်တည်နေရာကို ရှာဖွေပြီး ဂြိုလ်တု ရာသီဥတုဒေတာနှင့် စမတ် သီးနှံ အကြံပြုချက်ကို ရယူပါ။",
    "crop.soilPh": "မြေဆီလွှာ pH အဆင့်",
    "crop.rainfall": "မိုးရေချိန် (၇ ရက်, mm)",
    "crop.temp": "ပျမ်းမျှ အပူချိန် (°C)",
    "crop.analyzing": "ခွဲခြမ်းစိတ်ဖြာနေသည်...",
    "crop.suggestBtn": "အကြံပြုချက် ရယူရန်",
    "crop.recommended": "အကြံပြုထားသော သီးနှံ",
    "crop.analysis": "AI ခွဲခြမ်းစိတ်ဖြာချက်",
    "crop.fillForm": "သင့်တည်နေရာ ရှာဖွေပါ သို့မဟုတ် ကိုယ်တိုင် ထည့်သွင်းပြီး အကြံပြုချက် ရယူပါ။",
    "crop.error": "အကြံပြုချက် ရယူရန် မအောင်မြင်ပါ။ ML မော်ဒယ်နှင့် နောက်ကွယ်ပိုင်း အလုပ်လုပ်နေကြောင်း သေချာပါစေ။",

    // Location & Weather
    "loc.detect": "ကျွန်ုပ်၏ တည်နေရာ ရှာဖွေပါ",
    "loc.detecting": "တည်နေရာ ရှာဖွေနေသည်...",
    "loc.fetchWeather": "ဂြိုလ်တုဒေတာ ရယူနေသည်...",
    "loc.permDenied": "တည်နေရာ ခွင့်ပြုချက် ပြန်လည်ငြင်းပယ်ထားသည်။ GPS ဖွင့်ပါ သို့မဟုတ် ကိုယ်တိုင် ထည့်သွင်းပါ။",
    "loc.error": "တည်နေရာ ရှာမတွေ့ပါ။ ကိုယ်တိုင် ထည့်သွင်းပါ။",
    "loc.region": "ရှာဖွေတွေ့ရှိသော ဒေသ",
    "loc.coordinates": "ကိုဩဒိနိတ်",
    "loc.currentTemp": "လက်ရှိ အပူချိန်",
    "loc.rain7d": "မိုးရေချိန် (၇ ရက်)",
    "loc.humidity": "စိုထိုင်းဆ",
    "loc.soilPh": "ခန့်မှန်း မြေ pH",
    "loc.source": "ဒေတာ: NASA POWER ဂြိုလ်တု",
    "loc.phNote": "ဒေသတွင်း ခန့်မှန်းချက် — မြေစစ်ဆေးမှု ရလဒ်ရှိပါက ပြင်ဆင်ပါ",
    "loc.advisories": "စမတ် အကြံပြုချက်များ",
    "loc.override": "အကြံပြုချက် မရယူမီ တန်ဖိုးများ ပြင်ဆင်နိုင်ပါသည်",
    "loc.manualMode": "ကိုယ်တိုင် ထည့်သွင်းရန်",
    "loc.autoMode": "ဂြိုလ်တုဒေတာ သုံးရန်",

    // AI Chat
    "chat.title": "AI စကားပြောခန်း",
    "chat.powered": "Gemma 4 (စက်တွင်း AI) ဖြင့် ဖြေဆိုသည်",
    "chat.placeholder": "စိုက်ပျိုးရေး၊ သီးနှံများ၊ ရာသီဥတုအကြောင်း မေးမြန်းပါ...",
    "chat.error": "ဆာဗာသို့ ချိတ်ဆက်၍ မရပါ။",
  "chat.welcome": "မင်္ဂလာပါ။ မြန်မာနိုင်ငံ စိုက်ပျိုးရေးဆိုင်ရာ မေးခွန်းတွေကို ကူညီဖြေကြားပေးပါမယ်။ ဘာအကြောင်း မေးချင်ပါသလဲ?",
  "chat.history": "စကားပြောမှတ်တမ်း",
  "chat.newChat": "စကားပြောခန်းအသစ်",
  "chat.noHistory": "သိမ်းဆည်းထားသော စကားပြောခန်းများကို ဤနေရာတွင် တွေ့ရပါမည်။",
  "chat.signInHistory": "ဤစက်တွင် သိမ်းထားပါသည်။ အကောင့်ဝင်ပါက အကောင့်နှင့်ပါ ချိတ်ဆက်သိမ်းဆည်းပေးပါမည်။",
  "chat.historyError": "စကားပြောမှတ်တမ်းကို ရယူ၍ မရပါ။",
  "chat.saveError": "အဖြေကို ရရှိသော်လည်း စကားပြောခန်းကို သိမ်းဆည်း၍ မရပါ။",
  "chat.deleteError": "ဤစကားပြောခန်းကို ဖျက်၍ မရပါ။",
  "chat.deleteChat": "စကားပြောခန်းကို ဖျက်ရန်",
  "chat.deleteConfirm": "ဤစကားပြောခန်းကို အပြီးတိုင် ဖျက်မည်လား။",
  "chat.send": "စာပို့ရန်",

    // Auth
    "auth.welcomeBack": "ပြန်လည်ကြိုဆိုပါသည်",
    "auth.createAccount": "အကောင့်ဖန်တီးပါ",
    "auth.loginSubtitle": "သင့် GreenVista ဒက်ရှ်ဘုတ်သို့ ဝင်ရောက်ရန် အကောင့်ဝင်ပါ",
    "auth.registerSubtitle": "GreenVista တွင်ပါဝင်ပြီး သင့်လယ်ယာကို စီမံခန့်ခွဲပါ",
    "auth.loginBtn": "အကောင့်ဝင်ရန်",
    "auth.registerBtn": "အကောင့်ဖွင့်ရန်",
    "auth.logout": "ထွက်ရန်",
    "auth.fillFields": "ကျေးဇူးပြု၍ အချက်အလက်အားလုံးကို ဖြည့်စွက်ပါ",
    "auth.passwordMismatch": "စကားဝှက်များ မကိုက်ညီပါ",
    "auth.email": "အီးမေးလ် လိပ်စာ",
    "auth.password": "စကားဝှက်",
    "auth.confirmPassword": "စကားဝှက် အတည်ပြုပါ",
  }
};

const myOverrides = {
  "ndvi.outsideMyanmar": "မြန်မာနိုင်ငံအတွင်းကို နှိပ်၍ ခွဲခြမ်းစိတ်ဖြာမည့် ဒေသကို ရွေးချယ်ပါ။",
  "ndvi.location": "NDVI တည်နေရာ",
  "ndvi.stateRegion": "ပြည်နယ် သို့မဟုတ် တိုင်းဒေသကြီး",
  "ndvi.districtDetail": "ခရိုင်အသေးစိတ် (ရွေးချယ်နိုင်သည်)",
  "ndvi.allDistricts": "ခရိုင်အားလုံး (ပြည်နယ်အနှစ်ချုပ်)",
  "ndvi.loadingData": "NDVI အချက်အလက်များကို ရယူနေသည်...",
  "crop.suitable": "သင့်တော်မှု",
}

Object.assign(myOverrides, {
  "crop.farmArea": "လယ်ယာဧရိယာ (ဧက)",
  "nav.home": "ပင်မစာမျက်နှာ",
  "nav.fieldHealth": "စိုက်ခင်းကျန်းမာရေး",
  "nav.cropPlanner": "သီးနှံစိုက်ပျိုးမှု စီမံကိန်း",
  "nav.cropGuide": "သီးနှံ လမ်းညွှန်",
  "nav.aiGuide": "AI လမ်းညွှန်",
  "nav.workspace": "လုပ်ငန်းခွင်",
  "nav.farmIntelligence": "စိုက်ပျိုးရေး အချက်အလက်စနစ်",
  "nav.sidebarDescription": "ပိုမိုကောင်းမွန်သော သီးနှံနှင့် စိုက်ခင်းဆုံးဖြတ်ချက်များအတွက် တိကျသည့် ကိရိယာများ။",
  "nav.navigate": "လမ်းညွှန် ပုံဖော်ရန်",
  "nav.close": "လမ်းညွှန် ပိတ်ရန်",
  "nav.open": "လမ်းညွှန် ဖွင့်ရန်",
  "nav.mobileFooter": "ပိုမိုရှင်းလင်းသော စိုက်ပျိုးရေး ဆုံးဖြတ်ချက်များအတွက် စိုက်ခင်းအချက်အလက်။",
  "crop.pageEyebrow": "စမတ် သီးနှံစိုက်ပျိုးမှု စီမံကိန်း",
  "crop.benefitSatellite": "ဂြိုဟ်တု ရာသီဥတု အချက်အလက်",
  "crop.benefitLocal": "ဒေသတွင်း အခြေအနေများ",
  "crop.benefitGuidance": "လက်တွေ့ကျသော လမ်းညွှန်ချက်များ",
  "crop.fieldData": "စိုက်ခင်း အချက်အလက်",
  "crop.chooseSource": "အချက်အလက် ရယူမည့် နည်းလမ်းကို ရွေးချယ်ပါ",
  "crop.currentLocation": "လက်ရှိ စိုက်ခင်းတည်နေရာကို အသုံးပြုရန်",
  "crop.retrieveWeather": "သင်၏ တည်နေရာ အမှတ်စဉ်များမှ ဒေသတွင်း ရာသီဥတု အခြေအနေကို ရယူပါ။",
  "crop.ownMeasurements": "မိမိကိုယ်တိုင် တိုင်းတာထားသော အချက်အလက်များကို အသုံးပြုရန်",
  "crop.enterReadings": "နောက်တစ်ဆင့်တွင် လတ်တလော တိုင်းတာထားသော မြေဆီလွှာနှင့် ရာသီဥတု အချက်အလက်များကို ဖြည့်သွင်းပါ။",
  "crop.growingConditions": "စိုက်ပျိုးရေး အခြေအနေများ",
  "crop.reviewField": "စိုက်ခင်းကို ပြန်လည်စစ်ဆေးရန်",
  "crop.currentConditions": "လက်ရှိ အခြေအနေများပေါ် မူတည်၍",
  "crop.growingProfile": "စိုက်ပျိုးမှုဆိုင်ရာ အချက်အလက်",
  "crop.yearGrowth": "နှစ်အလိုက် စိုက်ပျိုးကာလ",
  "crop.waterNeed": "တစ်ရက်လျှင် လိုအပ်သော ရေပမာဏ (ယူနစ်)",
  "crop.latestMarketPrice": "နောက်ဆုံး ပေါက်စျေး",
  "crop.chooseCrop": "အကြံပြုထားသော သီးနှံကို ရွေးချယ်ပါ",
  "crop.option": "ရွေးချယ်စရာ",
  "crop.marketValue": "စျေးကွက်တန်ဖိုး",
  "crop.productWeight": "ထွက်ရှိမည့် အလေးချိန် (ကီလိုဂရမ်)",
  "crop.estimatedValue": "ခန့်မှန်းခြေ တန်ဖိုး",
  "crop.suitable": "သင့်တော်သော",
  "common.close": "ပိတ်ရန်",
  "ndvi.location": "NDVI တည်နေရာ",
  "ndvi.stateRegion": "ပြည်နယ် သို့မဟုတ် တိုင်းဒေသကြီး",
  "ndvi.districtDetail": "ခရိုင် အသေးစိတ် (စိတ်ကြိုက်)",
  "ndvi.allDistricts": "ခရိုင်အားလုံး (ပြည်နယ်/တိုင်း အကျဉ်းချုပ်)",
  "ndvi.loadingData": "NDVI အချက်အလက်များ ရယူနေပါသည်..."
});

Object.assign(myOverrides, {
  "auth.fillFields": "အချက်အလက်အားလုံးကို ဖြည့်စွက်ပါ။",
  "auth.passwordMismatch": "စကားဝှက်များ မကိုက်ညီပါ။",
  "auth.userExists": "ဤအီးမေးလ်ဖြင့် အကောင့်ရှိပြီးသားဖြစ်ပါသည်။",
  "auth.invalidCredentials": "အီးမေးလ် သို့မဟုတ် စကားဝှက် မှားယွင်းနေပါသည်။",
  "auth.emailInvalid": "မှန်ကန်သော အီးမေးလ်လိပ်စာကို ထည့်သွင်းပါ။",
  "auth.passwordTooShort": "စကားဝှက်သည် အနည်းဆုံး စာလုံး ၈ လုံး ရှိရပါမည်။",
  "auth.emailDeliveryFailed": "အကောင့်ဖန်တီးပြီးပါပြီ၊ သို့သော် အီးမေးလ်ပို့၍ မရပါ။"
  ,"auth.noAccount": "အကောင့်မရှိသေးပါသလား?"
  ,"auth.haveAccount": "အကောင့်ရှိပြီးသားလား?"
  ,"auth.switchSignup": "အကောင့်ဖွင့်ရန်"
  ,"auth.switchSignin": "အကောင့်ဝင်ရန်"
});

Object.assign(myOverrides, {
  "account.setupProfile": "သင့်လယ်ယာပရိုဖိုင်ကို စတင်သတ်မှတ်ပါ",
  "account.editProfile": "လယ်ယာပရိုဖိုင် ပြင်ဆင်ရန်",
  "account.requiredProfile": "သင့်လုပ်ငန်းခွင်ကို စိတ်ကြိုက်ပြင်ဆင်ရန် လယ်ယာအမည်၊ တည်နေရာ၊ ဧရိယာနှင့် မြေအမျိုးအစားကို ဖြည့်ပါ။",
  "account.farmLocation": "ပြည်နယ်/တိုင်းနှင့် ခရိုင်",
  "account.chooseLocation": "ပြည်နယ်/တိုင်းနှင့် ခရိုင်ကို ရွေးချယ်ပါ",
  "account.soilPlaceholder": "မြေအမျိုးအစားကို ရွေးချယ်ပါ သို့မဟုတ် ရိုက်ထည့်ပါ",
  "account.soilHelp": "သင့်ဒေသတွင် လယ်သမားများ အများအားဖြင့် ခေါ်သော မြေအမည်ကို ရွေးချယ်ပါ။",
  "crop.chooseOnMap": "မြေပုံပေါ်တွင် တည်နေရာရွေးချယ်ရန်",
  "crop.mapHint": "ရာသီဥတုနှင့် မြေဆီလွှာအခြေအနေကို ရယူရန် မြေပုံပေါ်ရှိနေရာကို နှိပ်ပါ။",
  "account.kicker": "တောင်သူ အကောင့်",
  "account.title": "ကျွန်ုပ်၏ လယ်ယာလုပ်ငန်းခွင်",
  "account.subtitle": "သင့်လယ်ယာအချက်အလက်များကို သိမ်းဆည်းပြီး အသုံးဝင်သော ဆန်းစစ်ချက်များသို့ လျင်မြန်စွာ ပြန်လည်ဝင်ရောက်ပါ။",
  "account.farmProfile": "လယ်ယာ ပရိုဖိုင်",
  "account.farmName": "လယ်ယာအမည်",
  "account.area": "လယ်ယာဧရိယာ (ဧက)",
  "account.soilType": "မြေအမျိုးအစား",
  "account.notes": "မှတ်ချက်များ",
  "account.saveProfile": "ပရိုဖိုင် သိမ်းဆည်းရန်",
  "account.favorites": "နှစ်သက်သော သီးနှံများ",
  "account.history": "အကြံပြုချက် မှတ်တမ်း",
  "account.noFavorites": "အကြံပြုချက်တစ်ခုမှ သီးနှံကို နှစ်သက်ရာအဖြစ် သတ်မှတ်ပါက ဤနေရာတွင် ပေါ်လာမည်။",
  "account.noHistory": "သိမ်းဆည်းထားသော အကြံပြုချက်များ ဤနေရာတွင် ပေါ်လာမည်။",
  "account.saved": "လယ်ယာပရိုဖိုင် သိမ်းဆည်းပြီးပါပြီ။",
  "account.analysisSaved": "ဆန်းစစ်ချက်ကို သင့်အကောင့်တွင် သိမ်းဆည်းပြီးပါပြီ။",
  "account.cropSaved": "သီးနှံကို နှစ်သက်ရာစာရင်းသို့ ထည့်ပြီးပါပြီ။",
  "account.saveAnalysis": "ဆန်းစစ်ချက် သိမ်းဆည်းရန်",
  "account.favorite": "သီးနှံကို နှစ်သက်ရာအဖြစ် သတ်မှတ်ရန်",
  "account.signInToSave": "သိမ်းဆည်းရန် အကောင့်ဝင်ပါ",
  "account.farmPlaceholder": "ဥပမာ - မိသားစုပိုင်လယ်ယာ",
  "account.acres": "ဧက",
  "account.removeFavorite": "{crop} ကို ဖယ်ရှားရန်",
  "account.requestError": "သင့်အကောင့်ကို ပြင်ဆင်၍ မရပါ။",
  "common.loading": "သင့်လုပ်ငန်းခွင်ကို ဖွင့်နေပါသည်...",
  "nav.workspaceNavigation": "လုပ်ငန်းခွင် လမ်းညွှန်",
  "nav.mobileWorkspaceNavigation": "မိုဘိုင်း လုပ်ငန်းခွင် လမ်းညွှန်",
  "nav.workspaceSidebar": "လုပ်ငန်းခွင် ဘေးဘက်လမ်းညွှန်",
  "brand.home": "GreenVista ပင်မစာမျက်နှာ",
  "language.selector": "ဘာသာစကား ရွေးချယ်ရန်",
  "common.skipToMain": "အဓိကအကြောင်းအရာသို့ ကျော်သွားရန်",
  "auth.closeDialog": "အကောင့်ဝင်ရန် ဝင်းဒိုးကို ပိတ်ရန်",
  "auth.showPassword": "စကားဝှက် ပြရန်",
  "auth.hidePassword": "စကားဝှက် ဝှက်ရန်",
  "auth.showConfirmPassword": "အတည်ပြုစကားဝှက် ပြရန်",
  "auth.hideConfirmPassword": "အတည်ပြုစကားဝှက် ဝှက်ရန်",
  "crop.plannerBenefits": "စီမံကိန်း၏ အကျိုးကျေးဇူးများ",
  "crop.modelConfidence": "မော်ဒယ် ယုံကြည်နိုင်မှု",
  "crop.bestSeason": "အကောင်းဆုံး ရာသီ",
  "crop.harvestTime": "ရိတ်သိမ်းချိန်",
  "crop.waterNeedLabel": "ရေလိုအပ်ချက်",
  "crop.varies": "အခြေအနေအလိုက် ကွဲပြားသည်",
  "crop.dialogLabel": "သီးနှံ အကြံပြုချက်",
  "crop.projectHistory": "စီမံကိန်း မှတ်တမ်း",
  "crop.rangeError": "{field} သည် {min} နှင့် {max}{unit} ကြားတွင် ရှိရပါမည်။",
  "crop.invalidNumbers": "သီးနှံအခြေအနေအားလုံးအတွက် မှန်ကန်သော ကိန်းဂဏန်းများကို ဖြည့်ပါ။",
  "crop.fallbackMatch": "ပေးထားသော အခြေအနေများအရ {crop} သည် စည်းမျဉ်းအခြေပြု အကောင်းဆုံး ကိုက်ညီသည့် သီးနှံဖြစ်သည်။",
  "crop.suggestionError": "သီးနှံအကြံပြုချက်ကို ရယူ၍ မရပါ။",
  "requirements.eyebrow": "သီးနှံအချက်အလက်",
  "requirements.pageTitle": "သီးနှံတိုင်း၏ လိုအပ်ချက်များကို လေ့လာပါ။",
  "requirements.pageSubtitle": "မည်သည့်သီးနှံ စိုက်ပျိုးမည်ကို မရွေးချယ်မီ လက်တွေ့စိုက်ပျိုးရေး အခြေအနေများကို လေ့လာပါ။",
  "requirements.searchEyebrow": "သီးနှံ အချက်အလက်စာရင်းတွင် ရှာဖွေပါ",
  "requirements.title": "သီးနှံ၏ စိုက်ပျိုးရန်လိုအပ်ချက်များကို ရှာဖွေပါ",
  "requirements.subtitle": "သီးနှံတစ်မျိုးအတွက် လိုအပ်သော ပျမ်းမျှရာသီဥတုနှင့် အလင်းရောင်အခြေအနေများကို ကြည့်ရှုရန် ရှာဖွေပါ။",
  "requirements.searchLabel": "သီးနှံအမည်",
  "requirements.placeholder": "စပါး၊ ပြောင်း၊ ပူစီနံ စသည်ဖြင့် ရှာဖွေပါ...",
  "requirements.search": "သီးနှံ ရှာဖွေရန်",
  "requirements.searching": "ရှာဖွေနေသည်...",
  "requirements.enterCrop": "ရှာဖွေရန် သီးနှံအမည် ထည့်ပါ။",
  "requirements.notFound": "ကိုက်ညီသော သီးနှံကို မတွေ့ပါ။",
  "requirements.error": "သီးနှံလိုအပ်ချက်များကို ရယူ၍ မရပါ။",
  "requirements.resultFor": "စိုက်ပျိုးရန် လိုအပ်ချက်များ",
  "requirements.temperature": "ပျမ်းမျှ အပူချိန်",
  "requirements.waterNeed": "ရေလိုအပ်ချက်",
  "requirements.soilPh": "ပျမ်းမျှ မြေဆီလွှာ pH",
  "requirements.humidity": "ပျမ်းမျှ စိုထိုင်းဆ",
  "requirements.light": "အလင်းရောင် လိုအပ်ချက်",
  "requirements.empty": "နှစ်သက်သော စိုက်ပျိုးရေးအခြေအနေများကို ကြည့်ရှုရန် သီးနှံတစ်မျိုး ရှာဖွေပါ။",
  "requirements.suggestionsLabel": "သီးနှံအမည် အကြံပြုချက်များ",
  "requirements.popularSuggestions": "လူရှာများသော သီးနှံများ",
  "requirements.matchingSuggestions": "ကိုက်ညီသော သီးနှံများ",
  "auth.requestError": "အကောင့်ဝင်ခြင်းကို ဆောင်ရွက်၍ မရပါ။ ထပ်မံကြိုးစားပါ။",
  "ndvi.regionsError": "NDVI ဒေသများကို ရယူ၍ မရပါ။",
  "ndvi.measurementsError": "ဤဒေသအတွက် NDVI တိုင်းတာချက်များကို ရယူ၍ မရပါ။",
  "requirements.suitableRegions": "သင့်လျော်နိုင်သော တိုင်းဒေသကြီး/ပြည်နယ်များ",
  "requirements.suitableRegionsHint": "ပရောဂျက်ရှိ ရာသီဥတု၊ သီးနှံမှတ်တမ်းနှင့် မြန်မာနယ်နိမိတ်ဒေတာများကို အခြေခံ၍ ခန့်မှန်းထားသည်။",
  "requirements.matchSuffix": "% ကိုက်ညီမှု",
  "requirements.regionCaveat": "ဒေသအလိုက် လမ်းညွှန်ချက်အဖြစ် အသုံးပြုပြီး မိမိမြို့နယ်၏ လက်ရှိမြေပြင်အခြေအနေကိုလည်း စစ်ဆေးပါ။",
});

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  const t = (key) => {
    return (language === 'my' ? myOverrides[key] : null) || translations[language][key] || translations['en'][key] || key;
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'my' : 'en');
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
